export const GET_ALL_COUNTRIES = 'GET_ALL_COUNTRIES';
export const FILTER_COUNTRIES_BY_CONTINENT = 'FILTER_COUNTRIES_BY_CONTINENT';
export const FILTER_COUNTRIES_BY_ACTIVITIES = 'FILTER_COUNTRIES_BY_ACTIVITIES';
export const ORDER_BY_NAME_OR_POPULATION = 'ORDER_BY_NAME_OR_POPULATION';
export const GET_COUNTRY_DETAIL = 'GET_COUNTRY_DETAIL';
export const GET_COUNTRY_BY_NAME = 'GET_COUNTRY_BY_NAME';